### PR TITLE
move app-password to dotenv file

### PR DESCRIPTION
**Pull request by nickdepinet**
This is a simple PR moving the app password to be pulled from the dotenv file for the publishFeedGen script. This will help prevent accidental password checkins, since the dotenv file is by default included in the gitignore.

### CODE REVIEW

**Comment by nickdepinet** [comment]
@dholms

**Comment by mackuba** [comment]
Would it maybe make more sense to just read it from STDIN (in some password entering mode that hides typed characters)? Publishing a feed is something that will usually only be done once and then maybe a couple of times at most when editing the name/description, so even having it in an .env file in plain text feels like unnecessary risk for basically zero added convenience. (I have no idea how to do this in Node)

**Comment by mackuba** [comment]
Something like this https://www.npmjs.com/package/password-prompt

**Comment by haileyok** [comment]
Got something merged in to use inquirer now.

**Pull request closed without merging**
